export const eventTypeOptions = [
  { value: 'KimaniEvent', label: 'Kimani event' },
  { value: 'MembersEvent', label: 'Members event' },
  { value: 'Other', label: 'Other event' }
];

export const planOptions = [
  { value: 'free', label: 'Free' },
  { value: 'pro', label: 'Pro' },
  { value: 'enterprise', label: 'Enterprise' }
];

export const cityOptions = [
  { value: 'Akron, OH', label: 'Akron, OH' },
  { value: 'Albuquerque, NM', label: 'Albuquerque, NM' },
  { value: 'Alexandria, VA', label: 'Alexandria, VA' },
  { value: 'Amarillo, TX', label: 'Amarillo, TX' },
  { value: 'Anaheim, CA', label: 'Anaheim, CA' },
  { value: 'Anchorage, AK', label: 'Anchorage, AK' },
  { value: 'Ann Arbor, MI', label: 'Ann Arbor, MI' },
  { value: 'Atlanta, GA', label: 'Atlanta, GA' },
  { value: 'Augusta, GA', label: 'Augusta, GA' },
  { value: 'Aurora, CO', label: 'Aurora, CO' },
  { value: 'Austin, TX', label: 'Austin, TX' },
  { value: 'Bakersfield, CA', label: 'Bakersfield, CA' },
  { value: 'Baltimore, MD', label: 'Baltimore, MD' },
  { value: 'Baton Rouge, LA', label: 'Baton Rouge, LA' },
  { value: 'Bellevue, WA', label: 'Bellevue, WA' },
  { value: 'Berkeley, CA', label: 'Berkeley, CA' },
  { value: 'Birmingham, AL', label: 'Birmingham, AL' },
  { value: 'Boise, ID', label: 'Boise, ID' },
  { value: 'Boston, MA', label: 'Boston, MA' },
  { value: 'Boulder, CO', label: 'Boulder, CO' },
  { value: 'Bridgeport, CT', label: 'Bridgeport, CT' },
  { value: 'Buffalo, NY', label: 'Buffalo, NY' },
  { value: 'Burlington, VT', label: 'Burlington, VT' },
  { value: 'Cambridge, MA', label: 'Cambridge, MA' },
  { value: 'Cape Coral, FL', label: 'Cape Coral, FL' },
  { value: 'Carlsbad, CA', label: 'Carlsbad, CA' },
  { value: 'Carrollton, TX', label: 'Carrollton, TX' },
  { value: 'Cary, NC', label: 'Cary, NC' },
  { value: 'Cedar Rapids, IA', label: 'Cedar Rapids, IA' },
  { value: 'Chandler, AZ', label: 'Chandler, AZ' },
  { value: 'Charleston, SC', label: 'Charleston, SC' },
  { value: 'Charlotte, NC', label: 'Charlotte, NC' },
  { value: 'Chattanooga, TN', label: 'Chattanooga, TN' },
  { value: 'Chesapeake, VA', label: 'Chesapeake, VA' },
  { value: 'Chicago, IL', label: 'Chicago, IL' },
  { value: 'Chula Vista, CA', label: 'Chula Vista, CA' },
  { value: 'Cincinnati, OH', label: 'Cincinnati, OH' },
  { value: 'Clarksville, TN', label: 'Clarksville, TN' },
  { value: 'Cleveland, OH', label: 'Cleveland, OH' },
  { value: 'Colorado Springs, CO', label: 'Colorado Springs, CO' },
  { value: 'Columbia, SC', label: 'Columbia, SC' },
  { value: 'Columbus, OH', label: 'Columbus, OH' },
  { value: 'Concord, CA', label: 'Concord, CA' },
  { value: 'Coral Springs, FL', label: 'Coral Springs, FL' },
  { value: 'Corona, CA', label: 'Corona, CA' },
  { value: 'Corpus Christi, TX', label: 'Corpus Christi, TX' },
  { value: 'Dallas, TX', label: 'Dallas, TX' },
  { value: 'Dayton, OH', label: 'Dayton, OH' },
  { value: 'Denton, TX', label: 'Denton, TX' },
  { value: 'Denver, CO', label: 'Denver, CO' },
  { value: 'Des Moines, IA', label: 'Des Moines, IA' },
  { value: 'Detroit, MI', label: 'Detroit, MI' },
  { value: 'Durham, NC', label: 'Durham, NC' },
  { value: 'El Paso, TX', label: 'El Paso, TX' },
  { value: 'Elizabeth, NJ', label: 'Elizabeth, NJ' },
  { value: 'Elk Grove, CA', label: 'Elk Grove, CA' },
  { value: 'Escondido, CA', label: 'Escondido, CA' },
  { value: 'Eugene, OR', label: 'Eugene, OR' },
  { value: 'Evansville, IN', label: 'Evansville, IN' },
  { value: 'Everett, WA', label: 'Everett, WA' },
  { value: 'Fairfield, CA', label: 'Fairfield, CA' },
  { value: 'Fargo, ND', label: 'Fargo, ND' },
  { value: 'Fayetteville, NC', label: 'Fayetteville, NC' },
  { value: 'Fort Collins, CO', label: 'Fort Collins, CO' },
  { value: 'Fort Lauderdale, FL', label: 'Fort Lauderdale, FL' },
  { value: 'Fort Wayne, IN', label: 'Fort Wayne, IN' },
  { value: 'Fort Worth, TX', label: 'Fort Worth, TX' },
  { value: 'Fremont, CA', label: 'Fremont, CA' },
  { value: 'Fresno, CA', label: 'Fresno, CA' },
  { value: 'Frisco, TX', label: 'Frisco, TX' },
  { value: 'Fullerton, CA', label: 'Fullerton, CA' },
  { value: 'Gainesville, FL', label: 'Gainesville, FL' },
  { value: 'Garden Grove, CA', label: 'Garden Grove, CA' },
  { value: 'Garland, TX', label: 'Garland, TX' },
  { value: 'Gilbert, AZ', label: 'Gilbert, AZ' },
  { value: 'Glendale, AZ', label: 'Glendale, AZ' },
  { value: 'Glendale, CA', label: 'Glendale, CA' },
  { value: 'Grand Prairie, TX', label: 'Grand Prairie, TX' },
  { value: 'Grand Rapids, MI', label: 'Grand Rapids, MI' },
  { value: 'Greensboro, NC', label: 'Greensboro, NC' },
  { value: 'Gresham, OR', label: 'Gresham, OR' },
  { value: 'Hampton, VA', label: 'Hampton, VA' },
  { value: 'Hartford, CT', label: 'Hartford, CT' },
  { value: 'Hayward, CA', label: 'Hayward, CA' },
  { value: 'Henderson, NV', label: 'Henderson, NV' },
  { value: 'Hialeah, FL', label: 'Hialeah, FL' },
  { value: 'High Point, NC', label: 'High Point, NC' },
  { value: 'Hollywood, FL', label: 'Hollywood, FL' },
  { value: 'Honolulu, HI', label: 'Honolulu, HI' },
  { value: 'Houston, TX', label: 'Houston, TX' },
  { value: 'Huntington Beach, CA', label: 'Huntington Beach, CA' },
  { value: 'Huntsville, AL', label: 'Huntsville, AL' },
  { value: 'Independence, MO', label: 'Independence, MO' },
  { value: 'Indianapolis, IN', label: 'Indianapolis, IN' },
  { value: 'Irvine, CA', label: 'Irvine, CA' },
  { value: 'Irving, TX', label: 'Irving, TX' },
  { value: 'Jackson, MS', label: 'Jackson, MS' },
  { value: 'Jacksonville, FL', label: 'Jacksonville, FL' },
  { value: 'Jersey City, NJ', label: 'Jersey City, NJ' },
  { value: 'Joliet, IL', label: 'Joliet, IL' },
  { value: 'Kansas City, MO', label: 'Kansas City, MO' },
  { value: 'Kent, WA', label: 'Kent, WA' },
  { value: 'Killeen, TX', label: 'Killeen, TX' },
  { value: 'Knoxville, TN', label: 'Knoxville, TN' },
  { value: 'Lafayette, LA', label: 'Lafayette, LA' },
  { value: 'Lakewood, CO', label: 'Lakewood, CO' },
  { value: 'Lancaster, CA', label: 'Lancaster, CA' },
  { value: 'Lansing, MI', label: 'Lansing, MI' },
  { value: 'Laredo, TX', label: 'Laredo, TX' },
  { value: 'Las Vegas, NV', label: 'Las Vegas, NV' },
  { value: 'Lexington, KY', label: 'Lexington, KY' },
  { value: 'Lincoln, NE', label: 'Lincoln, NE' },
  { value: 'Little Rock, AR', label: 'Little Rock, AR' },
  { value: 'Long Beach, CA', label: 'Long Beach, CA' },
  { value: 'Los Angeles, CA', label: 'Los Angeles, CA' },
  { value: 'Louisville, KY', label: 'Louisville, KY' },
  { value: 'Lowell, MA', label: 'Lowell, MA' },
  { value: 'Lubbock, TX', label: 'Lubbock, TX' },
  { value: 'Madison, WI', label: 'Madison, WI' },
  { value: 'Manchester, NH', label: 'Manchester, NH' },
  { value: 'McAllen, TX', label: 'McAllen, TX' },
  { value: 'Memphis, TN', label: 'Memphis, TN' },
  { value: 'Mesa, AZ', label: 'Mesa, AZ' },
  { value: 'Mesquite, TX', label: 'Mesquite, TX' },
  { value: 'Miami, FL', label: 'Miami, FL' },
  { value: 'Miami Gardens, FL', label: 'Miami Gardens, FL' },
  { value: 'Midland, TX', label: 'Midland, TX' },
  { value: 'Milwaukee, WI', label: 'Milwaukee, WI' },
  { value: 'Minneapolis, MN', label: 'Minneapolis, MN' },
  { value: 'Miramar, FL', label: 'Miramar, FL' },
  { value: 'Mobile, AL', label: 'Mobile, AL' },
  { value: 'Modesto, CA', label: 'Modesto, CA' },
  { value: 'Montgomery, AL', label: 'Montgomery, AL' },
  { value: 'Moreno Valley, CA', label: 'Moreno Valley, CA' },
  { value: 'Murfreesboro, TN', label: 'Murfreesboro, TN' },
  { value: 'Murrieta, CA', label: 'Murrieta, CA' },
  { value: 'Naperville, IL', label: 'Naperville, IL' },
  { value: 'Nashville, TN', label: 'Nashville, TN' },
  { value: 'New Haven, CT', label: 'New Haven, CT' },
  { value: 'New Orleans, LA', label: 'New Orleans, LA' },
  { value: 'New York, NY', label: 'New York, NY' },
  { value: 'Newark, NJ', label: 'Newark, NJ' },
  { value: 'Newport News, VA', label: 'Newport News, VA' },
  { value: 'Norfolk, VA', label: 'Norfolk, VA' },
  { value: 'Norman, OK', label: 'Norman, OK' },
  { value: 'North Las Vegas, NV', label: 'North Las Vegas, NV' },
  { value: 'Norwalk, CA', label: 'Norwalk, CA' },
  { value: 'Oakland, CA', label: 'Oakland, CA' },
  { value: 'Oceanside, CA', label: 'Oceanside, CA' },
  { value: 'Odessa, TX', label: 'Odessa, TX' },
  { value: 'Oklahoma City, OK', label: 'Oklahoma City, OK' },
  { value: 'Olathe, KS', label: 'Olathe, KS' },
  { value: 'Omaha, NE', label: 'Omaha, NE' },
  { value: 'Ontario, CA', label: 'Ontario, CA' },
  { value: 'Orange, CA', label: 'Orange, CA' },
  { value: 'Orlando, FL', label: 'Orlando, FL' },
  { value: 'Overland Park, KS', label: 'Overland Park, KS' },
  { value: 'Oxnard, CA', label: 'Oxnard, CA' },
  { value: 'Palm Bay, FL', label: 'Palm Bay, FL' },
  { value: 'Palmdale, CA', label: 'Palmdale, CA' },
  { value: 'Pasadena, CA', label: 'Pasadena, CA' },
  { value: 'Pasadena, TX', label: 'Pasadena, TX' },
  { value: 'Paterson, NJ', label: 'Paterson, NJ' },
  { value: 'Pearland, TX', label: 'Pearland, TX' },
  { value: 'Pembroke Pines, FL', label: 'Pembroke Pines, FL' },
  { value: 'Peoria, AZ', label: 'Peoria, AZ' },
  { value: 'Peoria, IL', label: 'Peoria, IL' },
  { value: 'Philadelphia, PA', label: 'Philadelphia, PA' },
  { value: 'Phoenix, AZ', label: 'Phoenix, AZ' },
  { value: 'Pittsburgh, PA', label: 'Pittsburgh, PA' },
  { value: 'Plano, TX', label: 'Plano, TX' },
  { value: 'Pomona, CA', label: 'Pomona, CA' },
  { value: 'Pompano Beach, FL', label: 'Pompano Beach, FL' },
  { value: 'Portland, OR', label: 'Portland, OR' },
  { value: 'Providence, RI', label: 'Providence, RI' },
  { value: 'Provo, UT', label: 'Provo, UT' },
  { value: 'Pueblo, CO', label: 'Pueblo, CO' },
  { value: 'Raleigh, NC', label: 'Raleigh, NC' },
  { value: 'Rancho Cucamonga, CA', label: 'Rancho Cucamonga, CA' },
  { value: 'Reno, NV', label: 'Reno, NV' },
  { value: 'Renton, WA', label: 'Renton, WA' },
  { value: 'Richmond, VA', label: 'Richmond, VA' },
  { value: 'Riverside, CA', label: 'Riverside, CA' },
  { value: 'Rochester, NY', label: 'Rochester, NY' },
  { value: 'Rockford, IL', label: 'Rockford, IL' },
  { value: 'Roseville, CA', label: 'Roseville, CA' },
  { value: 'Round Rock, TX', label: 'Round Rock, TX' },
  { value: 'Sacramento, CA', label: 'Sacramento, CA' },
  { value: 'Salem, OR', label: 'Salem, OR' },
  { value: 'Salinas, CA', label: 'Salinas, CA' },
  { value: 'Salt Lake City, UT', label: 'Salt Lake City, UT' },
  { value: 'San Antonio, TX', label: 'San Antonio, TX' },
  { value: 'San Bernardino, CA', label: 'San Bernardino, CA' },
  { value: 'San Diego, CA', label: 'San Diego, CA' },
  { value: 'San Francisco, CA', label: 'San Francisco, CA' },
  { value: 'San Jose, CA', label: 'San Jose, CA' },
  { value: 'San Mateo, CA', label: 'San Mateo, CA' },
  { value: 'Santa Ana, CA', label: 'Santa Ana, CA' },
  { value: 'Santa Clara, CA', label: 'Santa Clara, CA' },
  { value: 'Santa Clarita, CA', label: 'Santa Clarita, CA' },
  { value: 'Santa Rosa, CA', label: 'Santa Rosa, CA' },
  { value: 'Savannah, GA', label: 'Savannah, GA' },
  { value: 'Scottsdale, AZ', label: 'Scottsdale, AZ' },
  { value: 'Seattle, WA', label: 'Seattle, WA' },
  { value: 'Shreveport, LA', label: 'Shreveport, LA' },
  { value: 'Simi Valley, CA', label: 'Simi Valley, CA' },
  { value: 'Sioux Falls, SD', label: 'Sioux Falls, SD' },
  { value: 'South Bend, IN', label: 'South Bend, IN' },
  { value: 'Spokane, WA', label: 'Spokane, WA' },
  { value: 'Springfield, IL', label: 'Springfield, IL' },
  { value: 'Springfield, MO', label: 'Springfield, MO' },
  { value: 'St. Louis, MO', label: 'St. Louis, MO' },
  { value: 'St. Paul, MN', label: 'St. Paul, MN' },
  { value: 'St. Petersburg, FL', label: 'St. Petersburg, FL' },
  { value: 'Stamford, CT', label: 'Stamford, CT' },
  { value: 'Sterling Heights, MI', label: 'Sterling Heights, MI' },
  { value: 'Stockton, CA', label: 'Stockton, CA' },
  { value: 'Sunnyvale, CA', label: 'Sunnyvale, CA' },
  { value: 'Surprise, AZ', label: 'Surprise, AZ' },
  { value: 'Syracuse, NY', label: 'Syracuse, NY' },
  { value: 'Tacoma, WA', label: 'Tacoma, WA' },
  { value: 'Tallahassee, FL', label: 'Tallahassee, FL' },
  { value: 'Tampa, FL', label: 'Tampa, FL' },
  { value: 'Temecula, CA', label: 'Temecula, CA' },
  { value: 'Tempe, AZ', label: 'Tempe, AZ' },
  { value: 'Thornton, CO', label: 'Thornton, CO' },
  { value: 'Thousand Oaks, CA', label: 'Thousand Oaks, CA' },
  { value: 'Toledo, OH', label: 'Toledo, OH' },
  { value: 'Topeka, KS', label: 'Topeka, KS' },
  { value: 'Torrance, CA', label: 'Torrance, CA' },
  { value: 'Tucson, AZ', label: 'Tucson, AZ' },
  { value: 'Tulsa, OK', label: 'Tulsa, OK' },
  { value: 'Tyler, TX', label: 'Tyler, TX' },
  { value: 'Vallejo, CA', label: 'Vallejo, CA' },
  { value: 'Vancouver, WA', label: 'Vancouver, WA' },
  { value: 'Ventura, CA', label: 'Ventura, CA' },
  { value: 'Victorville, CA', label: 'Victorville, CA' },
  { value: 'Virginia Beach, VA', label: 'Virginia Beach, VA' },
  { value: 'Visalia, CA', label: 'Visalia, CA' },
  { value: 'Waco, TX', label: 'Waco, TX' },
  { value: 'Warren, MI', label: 'Warren, MI' },
  { value: 'Washington, DC', label: 'Washington, DC' },
  { value: 'Waterbury, CT', label: 'Waterbury, CT' },
  { value: 'West Covina, CA', label: 'West Covina, CA' },
  { value: 'West Jordan, UT', label: 'West Jordan, UT' },
  { value: 'West Palm Beach, FL', label: 'West Palm Beach, FL' },
  { value: 'West Valley City, UT', label: 'West Valley City, UT' },
  { value: 'Westminster, CO', label: 'Westminster, CO' },
  { value: 'Wichita, KS', label: 'Wichita, KS' },
  { value: 'Wichita Falls, TX', label: 'Wichita Falls, TX' },
  { value: 'Wilmington, NC', label: 'Wilmington, NC' },
  { value: 'Winston-Salem, NC', label: 'Winston-Salem, NC' },
  { value: 'Worcester, MA', label: 'Worcester, MA' },
  { value: 'Yonkers, NY', label: 'Yonkers, NY' }
];
