export const countryTimezones: Record<string, string> = {
  'United States': 'America/New_York',
  'Canada': 'America/Toronto',
  'United Kingdom': 'Europe/London',
  'France': 'Europe/Paris',
  'Germany': 'Europe/Berlin',
  'Spain': 'Europe/Madrid',
  'Italy': 'Europe/Rome',
  'Japan': 'Asia/Tokyo',
  'China': 'Asia/Shanghai',
  'India': 'Asia/Kolkata',
  'Australia': 'Australia/Sydney',
  'Brazil': 'America/Sao_Paulo',
  'Mexico': 'America/Mexico_City',
  'South Africa': 'Africa/Johannesburg',
  'Nigeria': 'Africa/Lagos',
  'Kenya': 'Africa/Nairobi',
  'Egypt': 'Africa/Cairo',
  'Saudi Arabia': 'Asia/Riyadh',
  'UAE': 'Asia/Dubai',
  'Singapore': 'Asia/Singapore',
  'South Korea': 'Asia/Seoul',
  'Russia': 'Europe/Moscow',
  'Turkey': 'Europe/Istanbul',
  'Netherlands': 'Europe/Amsterdam',
  'Sweden': 'Europe/Stockholm',
  'Norway': 'Europe/Oslo',
  'Denmark': 'Europe/Copenhagen',
  'Finland': 'Europe/Helsinki',
  'Poland': 'Europe/Warsaw',
  'Ukraine': 'Europe/Kiev',
  'Greece': 'Europe/Athens',
  'Portugal': 'Europe/Lisbon',
  'Ireland': 'Europe/Dublin',
  'Switzerland': 'Europe/Zurich',
  'Austria': 'Europe/Vienna',
  'Belgium': 'Europe/Brussels',
  'New Zealand': 'Pacific/Auckland',
  'Uruguay': 'America/Montevideo'
}; 